syntax = "proto3";

package safestake;

message CheckLivenessRequest {
    uint64 version = 1;
    bytes msg = 2;
    bytes validator_public_key = 3;
}

message CheckLivenessResponse {
    bytes signature = 1;
}

message GetSoftwareVersionRequest {
}

message GetSoftwareVersionResponse {
    uint64 software_vresion = 1;
}

message GetSignatureRequest {
    uint64 version = 1;
    bytes msg = 2;
    bytes validator_public_key = 3;
}

message GetSignatureResponse {
    bytes signature = 1;
}

message AttestRequest {
    uint64 version = 1;
    uint32 operator_id = 2;
    bytes domain_hash = 3;
    bytes domian_hash_signature = 4;
    bytes attestation_data = 5;
    bytes validator_public_key = 6;
}

message AttestResponse {
    string msg = 1;
}

message ProposeFullBlockRequest {
    uint64 version = 1;
    uint32 operator_id = 2;
    bytes domain_hash = 3;
    bytes domian_hash_signature = 4;
    bytes full_block_data = 5;
    bytes validator_public_key = 6;
}

message ProposeFullBlockResponse {
    string msg = 1;
}

message ProposeBlindedBlockRequest {
    uint64 version = 1;
    uint32 operator_id = 2;
    bytes domain_hash = 3;
    bytes domian_hash_signature = 4;
    bytes blinded_block_data = 5;
    bytes validator_public_key = 6;
}

message ProposeBlindedBlockResponse {
    string msg = 1;
}

message BroadcastAttestationRequest {
    uint64 version = 1;
    uint32 operator_id = 2;
    bytes domain_hash = 3;
    bytes domain_hash_signature = 4;
    bytes attestation = 5;
    uint64 validator_index = 6;
    bytes validator_public_key = 7;
}

message EmptyResponse {
}

message BroadcastAggregateAndProofRequest {
    uint64 version = 1;
    uint32 operator_id = 2;
    bytes domain_hash = 3;
    bytes domain_hash_signature = 4;
    bytes aggregate_and_proof = 5;
    bytes validator_public_key = 6;
}

message BroadcastSyncCommitteeMessageRequest {
    uint64 version = 1;
    uint32 operator_id = 2;
    bytes domain_hash = 3;
    bytes domain_hash_signature = 4;
    bytes sync_committee_message = 5;
    bytes validator_public_key = 6;
}

message BroadcastBlindedBlockRequest {
    uint64 version = 1;
    uint32 operator_id = 2;
    bytes domain_hash = 3;
    bytes domain_hash_signature = 4;
    bytes block_data = 5;
    bytes validator_public_key = 6;
}

message BroadcastFullBlockRequest {
    uint64 version = 1;
    uint32 operator_id = 2;
    bytes domain_hash = 3;
    bytes domain_hash_signature = 4;
    bytes block_data = 5;
    bytes blobs = 6;
    bytes validator_public_key = 7;
}

message SimpleDutyRequest {
    uint64 version = 1;
    uint32 operator_id = 2;
    bytes signing_root = 3;
    bytes signing_root_signature = 4;
    bytes validator_public_key = 5;
}


// Inference is the inference service.
service Safestake {
    rpc CheckLiveness(CheckLivenessRequest) returns (CheckLivenessResponse) {}
    rpc GetSignature(GetSignatureRequest) returns (GetSignatureResponse) {}
    rpc GetSignatureV2(GetSignatureRequest) returns (GetSignatureResponse) {}
    rpc AttestData(AttestRequest) returns (AttestResponse) {}
    rpc ProposeFullBlock(ProposeFullBlockRequest) returns (ProposeFullBlockResponse) {}
    rpc ProposeBlindedBlock(ProposeBlindedBlockRequest) returns (ProposeBlindedBlockResponse) {}
    rpc GetSoftwareVersion(GetSoftwareVersionRequest) returns (GetSoftwareVersionResponse) {}
    rpc BroadcastAttestation(BroadcastAttestationRequest) returns (EmptyResponse) {}
    rpc SimpleDuty(SimpleDutyRequest) returns (EmptyResponse) {}
    rpc BroadcastAggregateAndProof(BroadcastAggregateAndProofRequest) returns (EmptyResponse) {}
    rpc BroadcastSyncCommitteeMessage(BroadcastSyncCommitteeMessageRequest) returns (EmptyResponse) {}
    rpc BroadcastFullBlock(BroadcastFullBlockRequest) returns (EmptyResponse) {}
    rpc BroadcastBlindedBlock(BroadcastBlindedBlockRequest) returns (EmptyResponse) {}
}  

