[package]
name = "safestake_service"
version = "0.1.0"
edition = "2021"
authors = ["Zico <zhicong303@gmail.com", "Will <jianlinjiang@whu.edu.cn>"]

[dependencies]
account_utils = { workspace = true }
bincode = { workspace = true }
bls = { workspace = true }
directory = { workspace = true }
dirs = { workspace = true }
dvf_utils = { workspace = true }
eth2_keystore = { workspace = true }
eth2_keystore_share = { workspace = true }
hex = { workspace = true }
lighthouse_network = { workspace = true }
parking_lot = { workspace = true }
rand = { version = "0.8.5", features = ["small_rng"] }
reqwest = { workspace = true, features = ["native-tls"] }
safestake_crypto = { workspace = true }
safestake_operator = { workspace = true }
safestake_database = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_yaml = { workspace = true }
signing_method = { workspace = true }
slashing_protection = { workspace = true }
slot_clock = { workspace = true }
store = { workspace = true }
task_executor = { workspace = true }
tokio = { workspace = true }
types = { workspace = true }
validator_dir = { workspace = true, features = ["insecure_keys"] }
validator_store = { workspace = true }
warp_utils = { workspace = true }
validator_http_api = { workspace = true }
sensitive_url = { workspace = true }
eth2 ={ workspace = true }
safe_arith = { workspace = true }
tree_hash = { workspace = true }
beacon_node_fallback = { workspace = true }
either = { workspace = true }
tracing = { workspace = true }
lighthouse_validator_store = { workspace = true }

validator_manager = { path = "../../validator_manager" }
alloy-contract = "1.0"
alloy-primitives = { version = "1.4", features = ["serde"] }
alloy-provider = "1.0"
alloy-rpc-types = "1.0"
alloy-sol-macro = "1.4"
alloy-sol-types = "1.4"
alloy-transport-http = "1.0"
alloy-network = "1.0"
keccak-hash = "0.10.0"
tonic = "0.11"
base64 = "0.22.1"
secp256k1 = { version = "0.30.0", features = ["global-context", "std", "rand"] }